projects:
  mytasksdemo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/lib/api.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/lib
